-- ===========================================================================
-- TIPOS DE USUARIO: DE CUATRO NÚMEROS A FUEGO A UN CATÁLOGO
-- ===========================================================================
-- Fecha: 2026-10-09
-- Se aplica después de 2026-10-09_seguridad_archivos_por_grupo.sql.
--
-- users.type_user era una lista de cuatro valores escrita en el código de
-- Angular (1 SUPER USUARIO, 2 ADMINISTRADOR, 3 USUARIO SISTEMA, 4 USUARIO WEB)
-- y repetida en cinco pantallas. Decidía los permisos del gestor de archivos
-- hasta el fichero anterior, que lo pasó a los grupos; ahora el campo cambia
-- de oficio: pasa a decir QUÉ CLASE DE USUARIO ES —del sistema, de la página
-- web, freelance, temporal—, que es una pregunta distinta de «qué puede
-- hacer», y ésa la contestan el grupo y el perfil.
--
-- LOS DOS PRIMEROS VALORES NO SON CATEGORÍAS, son restos del oficio anterior:
-- «super usuario» y «administrador» describen poder, no clase de persona. Se
-- quedan en el catálogo pero INACTIVOS, para que el historial siga
-- resolviéndose —la auditoría guarda type_user en sus jsonb— y para que la
-- clave ajena no se rompa. Los dos usuarios que tenían el 1 (LAGILA y
-- SISTEMAS-CUENCA, los dos personal interno) pasan a SISTEMA.
--
-- Para deshacer ese movimiento:
--   UPDATE seguridad.users SET type_user = 1 WHERE login_user IN ('LAGILA', 'SISTEMAS-CUENCA');
--
-- LOS IDS 3 Y 4 NO SE TOCAN y por eso no hay que mover 51 filas: ya querían
-- decir SISTEMA y WEB, que es justo lo que se busca. Los nuevos empiezan en 5.
--
-- EL GRUPO DEJA DE ESCRIBIR ESTE CAMPO. fn_grupos_modificar, cuando se marca
-- «Aplicar a sus usuarios», ponía type_user = 2/3/4 según el grupo fuera
-- administrador, de sistema o web. Con el oficio nuevo eso sería pisar la
-- categoría: un freelance puede estar en cualquier grupo. El grupo sigue
-- aplicando perfil y horario, que son suyos.
--
-- Idempotente.
-- ===========================================================================

-- ---------------------------------------------------------------------------
-- 1. El catálogo
-- ---------------------------------------------------------------------------
-- Mismo molde que ventas.gestiones_tipos, que es el catálogo que ya hay en la
-- casa: codigo + nombre + orden + activo y las cuatro columnas de auditoría.
--
-- El id es IDENTITY «BY DEFAULT» y no «ALWAYS» a propósito: los cuatro
-- primeros se insertan con su número de siempre, porque users.type_user ya los
-- tiene escritos.
CREATE TABLE IF NOT EXISTS seguridad.tipos_usuarios (
    id          integer     GENERATED BY DEFAULT AS IDENTITY,
    codigo      varchar(20) NOT NULL,
    nombre      varchar(60) NOT NULL,
    descripcion text,
    /** Clase de Font Awesome, para la ficha y las rejillas */
    icono       varchar(40),
    /** Clase de color del tema (bg-primary, bg-info...) para la etiqueta */
    color       varchar(30),
    orden       integer     NOT NULL DEFAULT 100,
    activo      boolean     NOT NULL DEFAULT true,

    created_at  timestamptz DEFAULT CURRENT_TIMESTAMP,
    updated_at  timestamptz DEFAULT CURRENT_TIMESTAMP,
    created_by  varchar(100),
    updated_by  varchar(100),

    CONSTRAINT pk_tipos_usuarios     PRIMARY KEY (id),
    CONSTRAINT uq_tipos_usuarios_cod UNIQUE (codigo),
    CONSTRAINT ck_tipos_usuarios_cod CHECK (codigo = UPPER(TRIM(codigo)) AND length(TRIM(codigo)) >= 3)
);

COMMENT ON TABLE seguridad.tipos_usuarios
    IS 'Qué clase de usuario es (del sistema, web, freelance, temporal). No da permisos: eso lo deciden el grupo y el perfil';

COMMENT ON COLUMN seguridad.users.type_user
    IS 'Clase de usuario: seguridad.tipos_usuarios. No da permisos';

-- Los tres disparadores de siempre de las tablas de seguridad
DROP TRIGGER IF EXISTS trigger_tipos_usuarios_set_users  ON seguridad.tipos_usuarios;
DROP TRIGGER IF EXISTS trigger_tipos_usuarios_updated_at ON seguridad.tipos_usuarios;
DROP TRIGGER IF EXISTS trg_tipos_usuarios_audit          ON seguridad.tipos_usuarios;

CREATE TRIGGER trigger_tipos_usuarios_set_users
    BEFORE INSERT OR UPDATE ON seguridad.tipos_usuarios
    FOR EACH ROW EXECUTE FUNCTION auditoria.fn_set_audit_users();

CREATE TRIGGER trigger_tipos_usuarios_updated_at
    BEFORE UPDATE ON seguridad.tipos_usuarios
    FOR EACH ROW EXECUTE FUNCTION auditoria.fn_update_updated_at_column();

CREATE TRIGGER trg_tipos_usuarios_audit
    AFTER INSERT OR UPDATE OR DELETE ON seguridad.tipos_usuarios
    FOR EACH ROW EXECUTE FUNCTION auditoria.fn_auditar_cambios();


-- ---------------------------------------------------------------------------
-- 2. Los tipos
-- ---------------------------------------------------------------------------
-- ON CONFLICT no toca el nombre ni el orden de lo que ya hubiera: si alguien
-- renombra «Freelance» desde la pantalla, volver a correr el fichero no se lo
-- pisa. Sólo se asegura de que las filas existan.
INSERT INTO seguridad.tipos_usuarios (id, codigo, nombre, descripcion, icono, color, orden, activo) VALUES
    (1, 'SUPER',     'Super usuario',            'Del oficio anterior del campo, cuando decidía permisos. No usar: los permisos los dan el grupo y el perfil', 'fa-solid fa-user-shield',  'bg-danger',    900, false),
    (2, 'ADMIN',     'Administrador',            'Del oficio anterior del campo. No usar: lo administrador lo dice el grupo',                                   'fa-solid fa-user-gear',    'bg-warning',   901, false),
    (3, 'SISTEMA',   'Usuario del sistema',      'Personal de la empresa que entra al CRM',                                                                     'fa-solid fa-user-tie',     'bg-primary',    10, true),
    (4, 'WEB',       'Usuario de la página web', 'Cliente o visitante que entra por la web, no al CRM',                                                          'fa-solid fa-globe',        'bg-info',       20, true),
    (5, 'FREELANCE', 'Freelance',                'Trabaja por cuenta propia para la empresa, sin ser de plantilla',                                             'fa-solid fa-user-clock',   'bg-success',    30, true),
    (6, 'TEMPORAL',  'Temporal',                 'Alta por un tiempo: reemplazo, pasantía, campaña o proyecto',                                                 'fa-solid fa-hourglass-half','bg-secondary', 40, true)
ON CONFLICT (id) DO NOTHING;

-- Que el autonumérico no choque con los seis de arriba
SELECT setval(pg_get_serial_sequence('seguridad.tipos_usuarios', 'id'),
              GREATEST((SELECT MAX(id) FROM seguridad.tipos_usuarios), 6));


-- ---------------------------------------------------------------------------
-- 3. Los usuarios que estaban en un valor que ya no es categoría
-- ---------------------------------------------------------------------------
UPDATE seguridad.users
   SET type_user = 3
 WHERE type_user IN (1, 2);

-- El default era 1, que ahora está retirado: lo normal al dar de alta desde el
-- CRM es personal del sistema
ALTER TABLE seguridad.users ALTER COLUMN type_user SET DEFAULT 3;

-- Y que no se pueda escribir un número que no existe
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_users_tipo_usuario') THEN
        ALTER TABLE seguridad.users
            ADD CONSTRAINT fk_users_tipo_usuario
            FOREIGN KEY (type_user) REFERENCES seguridad.tipos_usuarios(id);
    END IF;
END;
$$;


-- ---------------------------------------------------------------------------
-- 4. El nombre del tipo, para quien tenga que enseñarlo
-- ---------------------------------------------------------------------------
-- Una función y no un JOIN en cada sitio: las funciones que listan usuarios
-- arman su jsonb dentro de subconsultas donde no hay dónde colgar el JOIN.
CREATE OR REPLACE FUNCTION seguridad.fn_tipo_usuario_json(p_id integer)
RETURNS jsonb
LANGUAGE sql
STABLE
AS $function$
    SELECT jsonb_build_object('codigo', t.codigo, 'nombre', t.nombre,
                              'icono', t.icono, 'color', t.color, 'activo', t.activo)
      FROM seguridad.tipos_usuarios t WHERE t.id = p_id;
$function$;

COMMENT ON FUNCTION seguridad.fn_tipo_usuario_json(integer)
    IS 'Código, nombre, icono y color de un tipo de usuario, para enseñarlo sin repetir la lista en cada pantalla';


-- ---------------------------------------------------------------------------
-- 5. El catálogo, para la pantalla
-- ---------------------------------------------------------------------------
-- `en_uso` dice cuántos usuarios vivos lo tienen: es lo que hace falta para
-- avisar antes de desactivar un tipo.
CREATE OR REPLACE FUNCTION seguridad.fn_tipos_usuarios_listar(p_incluir_inactivos boolean DEFAULT false)
RETURNS jsonb
LANGUAGE plpgsql
STABLE
SECURITY DEFINER
AS $function$
DECLARE
    v_data jsonb;
BEGIN
    SELECT COALESCE(jsonb_agg(jsonb_build_object(
               'id',          t.id,
               'codigo',      t.codigo,
               'nombre',      t.nombre,
               'descripcion', t.descripcion,
               'icono',       t.icono,
               'color',       t.color,
               'orden',       t.orden,
               'activo',      t.activo,
               'en_uso',      (SELECT COUNT(*) FROM seguridad.users u
                                WHERE u.type_user = t.id AND u.deleted_at IS NULL)
           ) ORDER BY t.orden, t.nombre), '[]'::jsonb) INTO v_data
      FROM seguridad.tipos_usuarios t
     WHERE (p_incluir_inactivos OR t.activo);

    RETURN jsonb_build_object('success', true, 'message', 'Tipos de usuario obtenidos exitosamente', 'data', v_data);
EXCEPTION
    WHEN OTHERS THEN
        RETURN jsonb_build_object('success', false,
                                  'message', 'Error al obtener los tipos de usuario: ' || SQLERRM,
                                  'error_code', SQLSTATE);
END;
$function$;


-- ---------------------------------------------------------------------------
-- 6. Que el alta y la modificación validen contra el catálogo
-- ---------------------------------------------------------------------------
-- Las dos tenían la lista escrita dentro: `NOT IN (1, 2, 3, 4)`. Ahora
-- preguntan a la tabla, y además exigen que el tipo esté ACTIVO: un tipo
-- retirado se sigue leyendo en los usuarios viejos, pero no se puede poner en
-- uno nuevo.
--
-- Se parchean por sustitución sobre su propia definición: son de 216 y 240
-- líneas, de ellas cambia una, y copiarlas aquí sería mantener dos versiones.
DO $$
DECLARE
    v_nombre  text;
    v_def     text;
    v_nueva   text;
    v_cuantas int;

    c_vieja constant text := '    IF v_type_user NOT IN (1, 2, 3, 4) THEN';
    c_nueva constant text :=
'    IF NOT EXISTS (SELECT 1 FROM seguridad.tipos_usuarios t
                    WHERE t.id = v_type_user AND t.activo) THEN';
BEGIN
    FOREACH v_nombre IN ARRAY ARRAY['fn_usuarios_crear', 'fn_usuarios_modificar'] LOOP
        SELECT pg_get_functiondef(p.oid) INTO v_def
          FROM pg_proc p JOIN pg_namespace n ON n.oid = p.pronamespace
         WHERE n.nspname = 'seguridad' AND p.proname = v_nombre AND p.prokind = 'f';

        IF v_def IS NULL THEN
            RAISE NOTICE 'no existe %', v_nombre;
            CONTINUE;
        END IF;

        IF position('seguridad.tipos_usuarios' IN v_def) > 0 THEN
            RAISE NOTICE '% ya valida contra el catálogo', v_nombre;
            CONTINUE;
        END IF;

        v_cuantas := (length(v_def) - length(replace(v_def, c_vieja, ''))) / length(c_vieja);
        IF v_cuantas <> 1 THEN
            RAISE EXCEPTION '% : esperaba 1 validación del tipo y hay %', v_nombre, v_cuantas;
        END IF;

        v_nueva := replace(v_def, c_vieja, c_nueva);
        EXECUTE v_nueva;
        RAISE NOTICE '% actualizada', v_nombre;
    END LOOP;
END;
$$;


-- ---------------------------------------------------------------------------
-- 7. El grupo deja de escribir la categoría
-- ---------------------------------------------------------------------------
-- Cinco sitios de fn_grupos_modificar, todos dentro del bloque «Aplicar a sus
-- usuarios»: la variable, su cálculo, la condición que metía al usuario en el
-- lote sólo por el tipo, el jsonb de auditoría y el UPDATE. Perfil y horario
-- se quedan como están.
DO $$
DECLARE
    v_def     text;
    v_nueva   text;
    i         int;
    v_cuantas int;

    c_anclas text[] := ARRAY[
        '    v_type_user        integer;
',
        '        v_type_user := CASE WHEN COALESCE(p_es_administrador, false) THEN 2
                            WHEN COALESCE(p_tipo_acceso, ''SISTEMA'') = ''WEB'' THEN 4 ELSE 3 END;
',
        '                    OR (p_chorario_id IS NOT NULL AND u.chorario_id IS DISTINCT FROM p_chorario_id)
                    OR u.type_user IS DISTINCT FROM v_type_user)',
        '                ''type_user'',   v_type_user,
',
        '                   type_user   = v_type_user,
'
    ];
    c_nuevas text[] := ARRAY[
        '',
        '',
        '                    OR (p_chorario_id IS NOT NULL AND u.chorario_id IS DISTINCT FROM p_chorario_id))',
        '',
        ''
    ];
BEGIN
    SELECT pg_get_functiondef(p.oid) INTO v_def
      FROM pg_proc p JOIN pg_namespace n ON n.oid = p.pronamespace
     WHERE n.nspname = 'seguridad' AND p.proname = 'fn_grupos_modificar' AND p.prokind = 'f';

    IF v_def IS NULL THEN
        RAISE NOTICE 'no existe fn_grupos_modificar';
        RETURN;
    END IF;

    IF position('v_type_user' IN v_def) = 0 THEN
        RAISE NOTICE 'fn_grupos_modificar ya no toca type_user';
        RETURN;
    END IF;

    -- Primero se comprueban todas las anclas; sólo después se toca algo
    FOR i IN 1 .. array_length(c_anclas, 1) LOOP
        v_cuantas := (length(v_def) - length(replace(v_def, c_anclas[i], ''))) / length(c_anclas[i]);
        IF v_cuantas <> 1 THEN
            RAISE EXCEPTION 'fn_grupos_modificar : el ancla % aparece % veces y esperaba 1', i, v_cuantas;
        END IF;
    END LOOP;

    v_nueva := v_def;
    FOR i IN 1 .. array_length(c_anclas, 1) LOOP
        v_nueva := replace(v_nueva, c_anclas[i], c_nuevas[i]);
    END LOOP;

    IF position('v_type_user' IN v_nueva) > 0 THEN
        RAISE EXCEPTION 'fn_grupos_modificar : quedó alguna referencia a v_type_user';
    END IF;

    EXECUTE v_nueva;
    RAISE NOTICE 'fn_grupos_modificar actualizada: ya no escribe type_user';
END;
$$;


-- ---------------------------------------------------------------------------
-- 8. Que el nombre del tipo viaje con el usuario
-- ---------------------------------------------------------------------------
-- Igual que perfil_id lleva al lado perfil_nombre. Así las rejillas enseñan la
-- etiqueta sin repetir la lista: hoy la repiten cinco pantallas del front.
DO $$
DECLARE
    v_nombre  text;
    v_def     text;
    v_nueva   text;
    v_cuantas int;
    c_ancla   constant text := '''type_user'',         u.type_user,';
    c_ancla2  constant text := '''type_user'', t.type_user,';
BEGIN
    -- fn_usuarios_json: una sola vez, con su sangría propia
    SELECT pg_get_functiondef(p.oid) INTO v_def
      FROM pg_proc p JOIN pg_namespace n ON n.oid = p.pronamespace
     WHERE n.nspname = 'seguridad' AND p.proname = 'fn_usuarios_json' AND p.prokind = 'f';

    IF position('fn_tipo_usuario_json' IN v_def) > 0 THEN
        RAISE NOTICE 'fn_usuarios_json ya lleva el tipo';
    ELSE
        v_cuantas := (length(v_def) - length(replace(v_def, c_ancla, ''))) / length(c_ancla);
        IF v_cuantas <> 1 THEN
            RAISE EXCEPTION 'fn_usuarios_json : el ancla aparece % veces', v_cuantas;
        END IF;
        EXECUTE replace(v_def, c_ancla,
            c_ancla || '
        ''type_user_tipo'',    seguridad.fn_tipo_usuario_json(u.type_user),');
        RAISE NOTICE 'fn_usuarios_json actualizada';
    END IF;

    -- El listado paginado arma el objeto dos veces (con y sin búsqueda)
    SELECT pg_get_functiondef(p.oid) INTO v_def
      FROM pg_proc p JOIN pg_namespace n ON n.oid = p.pronamespace
     WHERE n.nspname = 'seguridad' AND p.proname = 'fn_usuarios_listar_paginado_activos' AND p.prokind = 'f';

    IF position('fn_tipo_usuario_json' IN v_def) > 0 THEN
        RAISE NOTICE 'fn_usuarios_listar_paginado_activos ya lleva el tipo';
    ELSE
        v_cuantas := (length(v_def) - length(replace(v_def, c_ancla2, ''))) / length(c_ancla2);
        IF v_cuantas <> 2 THEN
            RAISE EXCEPTION 'fn_usuarios_listar_paginado_activos : el ancla aparece % veces y esperaba 2', v_cuantas;
        END IF;
        -- replace cambia las dos de una vez, que es lo que se quiere
        EXECUTE replace(v_def, c_ancla2,
            c_ancla2 || '
                    ''type_user_tipo'', seguridad.fn_tipo_usuario_json(t.type_user),');
        RAISE NOTICE 'fn_usuarios_listar_paginado_activos actualizada';
    END IF;
END;
$$;


-- ---------------------------------------------------------------------------
-- 9. Y la ficha del usuario
-- ---------------------------------------------------------------------------
-- fn_usuarios_obtener es la que lee la pantalla de ver/editar, y arma su
-- propio objeto en vez de llamar a fn_usuarios_json, así que no heredó nada
-- del paso anterior. Las tres de listado sí lo heredan (comprobado llamándolas
-- después de aplicar: paginado, paginado_activos y por_grupo ya traen el tipo).
DO $$
DECLARE
    v_def     text;
    v_cuantas int;
    c_ancla   constant text := '        ''type_user'', u.type_user,';
BEGIN
    SELECT pg_get_functiondef(p.oid) INTO v_def
      FROM pg_proc p JOIN pg_namespace n ON n.oid = p.pronamespace
     WHERE n.nspname = 'seguridad' AND p.proname = 'fn_usuarios_obtener' AND p.prokind = 'f';

    IF v_def IS NULL THEN
        RAISE NOTICE 'no existe fn_usuarios_obtener';
        RETURN;
    END IF;

    IF position('fn_tipo_usuario_json' IN v_def) > 0 THEN
        RAISE NOTICE 'fn_usuarios_obtener ya lleva el tipo';
        RETURN;
    END IF;

    v_cuantas := (length(v_def) - length(replace(v_def, c_ancla, ''))) / length(c_ancla);
    IF v_cuantas <> 1 THEN
        RAISE EXCEPTION 'fn_usuarios_obtener : el ancla aparece % veces y esperaba 1', v_cuantas;
    END IF;

    EXECUTE replace(v_def, c_ancla, c_ancla || '
        ''type_user_tipo'', seguridad.fn_tipo_usuario_json(u.type_user),');
    RAISE NOTICE 'fn_usuarios_obtener actualizada';
END;
$$;


-- ---------------------------------------------------------------------------
-- COMPROBACIÓN
-- ---------------------------------------------------------------------------
SELECT t.id, t.codigo, t.nombre, t.activo,
       (SELECT COUNT(*) FROM seguridad.users u WHERE u.type_user = t.id AND u.deleted_at IS NULL) AS usuarios
  FROM seguridad.tipos_usuarios t ORDER BY t.orden, t.id;
