server {
    listen 80;
    server_name crm.aespana.com.ec;

    # --- FRONTEND ANGULAR ---
    root /var/www/crm/front/dist;
    index index.html;

    # Si la ruta existe la sirve, si no, reenvía a index.html (Angular SPA)
    location / {
        try_files $uri $uri/ /index.html;
    }


    # Logs opcionales
    access_log /var/log/nginx/front_access.log;
    error_log /var/log/nginx/front_error.log;
}
