map $http_upgrade $type {
  default "web";
  websocket "ws";
}

server {
    server_name api.aespana.com.ec 192.168.254.15;

    root /var/www/crm/back/public;
    index index.php;

    location / {
        try_files $uri $uri/ @web;
    }

    # Proxy WebSocket (conexión en tiempo real)
    location /app/ {
        proxy_pass http://127.0.0.1:6001;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "Upgrade";
        proxy_set_header Host $host;
        proxy_read_timeout 300;
        proxy_send_timeout 300;
        proxy_connect_timeout 300;
        proxy_redirect off;
        proxy_cache_bypass $http_upgrade;
    }
    
    # Endpoint de eventos (cuando Laravel emite)
    location /apps/ {
        proxy_pass http://127.0.0.1:6001;
        proxy_http_version 1.1;
        proxy_set_header Host $host;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "Upgrade";
        proxy_read_timeout 300;
    }
    
    # Panel WebSockets (opcional, útil para debug)
    location /laravel-websockets {
        proxy_pass http://127.0.0.1:6001;
        proxy_http_version 1.1;
        proxy_set_header Host $host;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "Upgrade";
        proxy_read_timeout 300;
    }

    location @web {
        try_files $uri $uri/ /index.php?$query_string;
    }


    location ~ \.php$ {
        include fastcgi_params;
        fastcgi_pass unix:/run/php-fpm/www.sock;
        fastcgi_index index.php;
        fastcgi_param SCRIPT_FILENAME $realpath_root$fastcgi_script_name;
        fastcgi_param DOCUMENT_ROOT $realpath_root;
        include fastcgi.conf;
    }

    location ~ /\.(?!well-known).* {
        deny all;
    }

    access_log /var/log/nginx/back_access.log;
    error_log /var/log/nginx/back_error.log;

    listen 443 ssl; # managed by Certbot
    ssl_certificate /etc/letsencrypt/live/api.aespana.com.ec/fullchain.pem; # managed by Certbot
    ssl_certificate_key /etc/letsencrypt/live/api.aespana.com.ec/privkey.pem; # managed by Certbot
    include /etc/letsencrypt/options-ssl-nginx.conf; # managed by Certbot
    ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem; # managed by Certbot

}


server {
    if ($host = api.aespana.com.ec) {
        return 301 https://$host$request_uri;
    } # managed by Certbot


    listen 80;
    server_name api.aespana.com.ec 192.168.254.15;
    return 404; # managed by Certbot


}